steps:
  # Docker 빌드 단계 - 수정된 부분
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hitmeup:$COMMIT_SHA', '.' ]

  # Docker 이미지 푸시 단계
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/hitmeup:$COMMIT_SHA' ]

  # Cloud Run 배포 단계
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hitmeup-backend'
      - '--image=gcr.io/$PROJECT_ID/hitmeup:$COMMIT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=prod'
      - '--set-secrets=FIREBASE_CONFIG=firebase-service-account:latest'
      - '--timeout=180s'  # 시작 타임아웃 늘리기

images:
  - 'gcr.io/$PROJECT_ID/hitmeup:$COMMIT_SHA'