steps:
  # Docker 빌드 단계
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/hit-me-up-336ec/hitmeup:latest', '.' ]

  # Docker 이미지 푸시 단계
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/hit-me-up-336ec/hitmeup:latest' ]

  # Cloud Run 배포 단계
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hitmeup-backend'
      - '--image=gcr.io/hit-me-up-336ec/hitmeup:latest'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=prod'
      - '--set-env-vars=APP_DOMAIN=https://hitmeup-backend-593087166771.asia-northeast1.run.app'
      - '--set-secrets=FIREBASE_CONFIG=firebase-service-account:latest'
      - '--timeout=300s'

images:
  - 'gcr.io/hit-me-up-336ec/hitmeup:latest'
