spring:
  application:
    name: Hit Me Up

#  # Redis
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      # password: "" // .env
#      # database: 0
#      repositories:
#        enabled: true

# ??
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

app:
  domain: ${APP_DOMAIN:http://localhost:8080}
  visitor:
    default-count: 0

logging:
  level:
    root: INFO
    com:
      hitmeup:
        backend: DEBUG