name: Keep Cloud Run Warm

on:
  schedule:
    # 매 10분마다 실행 (UTC 기준)
    - cron: '*/10 * * * *'
  
  # 수동 실행도 가능하게
  workflow_dispatch:

jobs:
  warm-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Warm up Cloud Run service
        run: |
          echo "Warming up the service..."
          curl -f -s -o /dev/null "https://hitmeup-backend-593087166771.asia-northeast1.run.app/api/ping" || echo "Warming request failed, but that's ok"
          echo "Warming completed"
        
      - name: Log warming time
        run: echo "Service warmed at $(date)"